apiVersion: batch/v1
kind: Job
metadata:
  name: e2e-test-trigger
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    metadata:
      labels:
        name: api-test
    spec:
      containers:
      - name: api-test
        image: curlimages/curl
        args:
            - /bin/sh
            - -ec
            - "curl -X POST -H \"Accept: application/vnd.github.v3+json\" -H \"Authorization: token ${GITHUB_TOKEN}\" ${GITHUB_URL} -d '{\"ref\":\"main\" ,\"inputs\": { \"environment\":\"${ENVIRONMENT}\",\"grepTags\": \"${GREPTAGS}\"}}'"
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
                name: github-token
                key: token
        - name: ENVIRONMENT
          value: test
        - name: GREPTAGS
          value: '@criticalPath'
        - name: GITHUB_URL
          value: "https://api.github.com/repos/SpidyParker/e2e-dispatch/actions/workflows/e2e.yaml/dispatches"
      restartPolicy: OnFailure