name: Run e2e-api test 

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select Environment
        required: true
        type: choice
        options:
        - dev
        - test
        - td
      grepTags:
         description: 'Test tags E.g @criticalPath or @regression|@criticalPath to select multiple tags'
         required: false
env:
  ENVIRONMENT: ${{ github.event.inputs.environment }}
  GREPTAGS: ${{ github.event.inputs.grepTags }}

jobs:
  run-e2e:
    name: run e2e
    runs-on: ubuntu-latest
    steps:
    - run: echo "$ENVIRONMENT $GREPTAGS"
